# fly.toml app configuration file generated for lov on 2023-08-19T12:31:06-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lov"
primary_region = "lax"
swap_size_mb = 512

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source = "litefs"
  destination = "/db"

[env]
  FAQ_DB_URL = "file:/db/faq.db"
